import { slh_dsa_shake_128f } from "@noble/post-quantum/slh-dsa";
import { promises as fs } from "fs";

async function readHexFileAsBytes(path) {
  try {
    // Read file content as a string
    const content = await fs.readFile(path, "utf-8");

    // Remove "0x" prefix if present
    const hexString = content.trim().startsWith("0x")
      ? content.trim().slice(2)
      : content.trim();

    // Convert hex string to Uint8Array
    const byteArray = new Uint8Array(
      hexString.match(/.{1,2}/g).map((byte) => parseInt(byte, 16))
    );

    return byteArray;
  } catch (error) {
    console.error("Error reading signature file:", error);
    throw error;
  }
}

async function readKeysFromJson(filePath) {
  try {
    // Read the file content as JSON
    const data = await fs.readFile(filePath, "utf-8");

    // Parse the JSON content
    const jsonData = JSON.parse(data);

    // Initialize key variable with publicKey and privateKey as Uint8Array
    const key = {
      publicKey: new Uint8Array(jsonData.pubkey),
      secretKey: new Uint8Array(jsonData.prikey),
    };

    return key;
  } catch (error) {
    console.error("Error reading keys from JSON:", error);
    throw error;
  }
}

// read the key that's generated from the C library
// by the sphincs+ team
const keys = await readKeysFromJson("./key.json");
console.log(">>>keys: ", keys);

// - using a signature generated by the c library
// - message to sign is in message.txt
// - output signature is in signature.txt
// - trim the last 32 bytes because the C implementation appended the message on it
const importedSignature = await readHexFileAsBytes("./signature.txt");
const signature = importedSignature.slice(0, importedSignature.length - 32);
const message = importedSignature.slice(
  importedSignature.length - 32,
  importedSignature.length
);

console.log(">>>importedSignature: ", importedSignature);

// read the message that was signed on by the C library
// by the sphincs+ team
// const message = await readFile('./message.txt');
// const message = await readHexFileAsBytes("./message.txt");
const originalMessage = await readHexFileAsBytes("./message.txt");
console.log(">>>the original message sphics+ signed: ", originalMessage.toString());
console.log(">>> message from sphincs-C signature: ", message.toString());

// verify
const isValid = slh_dsa_shake_128f.verify(keys.publicKey, message, signature);
console.log(">>>isValid: ", isValid);
